### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by Chirunos** [vegnuli/vegnuli#1]
Is VeGNUli still maintained?

**Comment by mckaygerhard** [comment]
repos are active.. isos are not so active..  OBS service has repos for debian 5 to debian 11, debian 12 still not had repos

**Comment by mckaygerhard** [comment]
@Gersonzao  we still suport some minimal packages for older releases, also devuan, and we have activity in telegram

**Comment by Chirunos** [comment]
> @Gersonzao we still suport some minimal packages for older releases, also devuan, and we have activity in telegram

That's nice. Apparently VeGNUli complies with FSDG just like VenenuX did, right? I'm still a bit confused about what's VeGNUli's current main goal; it was focused on multimedia and is nowadays focused in being lightweight?

**Comment by Chirunos** [comment]
Also, I don't yet have an account on Telegram mainly due to privacy concerns and its proprietary back-end :(

**Comment by mckaygerhard** [comment]
> > @Gersonzao we still suport some minimal packages for older releases, also devuan, and we have activity in telegram
> 
> That's nice. Apparently VeGNUli complies with FSDG just like VenenuX did, right? I'm still a bit confused about what's VeGNUli's current main goal; it was focused on multimedia and is nowadays focused in being lightweight?

one day RMS tells to MAster Vitronic _VenenuX does not honor GNU, must the name have GNU include so must be called VE**GNU**li_ (something like **Ve**nenux **GNU** **Li**nux) @Gersonzao 

currently the next iso will be at december..

**Comment by Chirunos** [comment]
> > > @Gersonzao we still suport some minimal packages for older releases, also devuan, and we have activity in telegram
> > 
> > 
> > That's nice. Apparently VeGNUli complies with FSDG just like VenenuX did, right? I'm still a bit confused about what's VeGNUli's current main goal; it was focused on multimedia and is nowadays focused in being lightweight?
> 
> one day RMS tells to MAster Vitronic _VenenuX does not honor GNU, must the name have GNU include so must be called VE**GNU**li_ (something like **Ve**nenux **GNU** **Li**nux) @Gersonzao
> 
> currently the next iso will be at december..

So VeGNUli (if that's the correct name) is basically a continuation to VenenuX?

**Comment by mckaygerhard** [comment]
something like that! but low activity.. 

the world of linux dont need more distros .. need more enterprice apps, curently google, mocosoft are killing all FREE SOFTWARE entrepreneur is being annihilated

by example @Gersonzao in old days you and me we can take a suite of mail like courier, some front end apps, interconnectiong all and provide a great service .. 

today: gmail, outlook , yahoo, nothing more, ...

**Comment by Chirunos** [comment]
> something like that! but low activity..
> 
> the world of linux dont need more distros .. need more enterprice apps, curently google, mocosoft are killing all FREE SOFTWARE entrepreneur is being annihilated
> 
> by example @Gersonzao in old days you and me we can take a suite of mail like courier, some front end apps, interconnectiong all and provide a great service ..
> 
> today: gmail, outlook , yahoo, nothing more, ...

Yeah, many corporations are slowly extinguishing Free Software. Unfortunately there aren't many active/popular fully free operating systems beside Trisquel and PureOS for some reason, but I'll give VeGNUli a try anyways. About email providers, I recently switched to Skiff Mail which is apparently 100% free, unlike Proton Mail and Tutanota which have some proprietary server-side code.

Before Skiff, I didn't yet switch from Gmail to Proton Mail because of some minor Proton concerns and I didn't know *much* about Tutanota (Tutanota has some bias in favor of itself when comparing itself to competitors [including privacy/freedom-focused providers like Skiff and Proton Mail]). I can say the ~~procrastination~~ wait was worth it.
